# -*- mode:python -*-


Import('*')

if env['CONF']['BUILD_ISA']:
    SimObject('BaseCClassCPU.py', sim_objects=['BaseCClassCPU'],
        enums=['CClassThreadPolicy'])

#    Source('activity.cc')
    Source('cpu.cc')
    Source('decode.cc')
#    Source('dyn_inst.cc')
#    Source('execute.cc')
    Source('fetch1.cc')
    Source('fetch2.cc')
#    Source('func_unit.cc')
#    Source('lsq.cc')
    Source('pipe_data.cc')
    Source('pipeline.cc')
#   Source('scoreboard.cc')
#    Source('stats.cc')

    DebugFlag('CClassCPU', 'CClass CPU-level events')
    DebugFlag('CClassFetch', 'CClass fetch stage')
#    DebugFlag('MinorExecute', 'Minor Execute stage')
#    DebugFlag('MinorInterrupt', 'Minor interrupt handling')
    DebugFlag('CClassMem', 'CClass memory accesses')
#    DebugFlag('MinorScoreboard', 'Minor Execute register scoreboard')
#    DebugFlag('MinorTrace', 'MinorTrace cycle-by-cycle state trace')
    DebugFlag('CClassTiming', 'Extra timing for instructions')

#    CompoundFlag('Minor', [
#        'MinorCPU', 'MinorExecute', 'MinorInterrupt', 'MinorMem',
#        'MinorScoreboard'])

    # For backwards compatibility
    SimObject('CClassCPU.py', sim_objects=[], tags=['isa'])
