#include "cpu/cclass/cpu.hh"
// #include "cpu/c_class/dyn_inst.hh"
#include "cpu/cclass/fetch1.hh"
#include "cpu/cclass/pipeline.hh"
// #include "debug/Drain.hh"   //auto-generated by gem5
#include "debug/CClassCPU.hh"
#include "debug/Quiesce.hh"

namespace gem5
{ 

CClassCPU::CClassCPU(const BaseCClassCPUParams &params):
    BaseCPU(params),
    threadPolicy(params.threadPolicy)
    //stats(this)
{
    /* This is only written for one thread at the moment */
    cclass::CClassThread *thread;

    for (ThreadID i = 0; i < numThreads; i++) {
        if (FullSystem) {
            thread = new cclass::CClassThread(this, i, params.system,
                    params.mmu, params.isa[i], params.decoder[i]);
            thread->setStatus(ThreadContext::Halted);
        } else {
            thread = new cclass::CClassThread(this, i, params.system,
                    params.workload[i], params.mmu,
                    params.isa[i], params.decoder[i]);
        }

        threads.push_back(thread);
        ThreadContext *tc = thread->getTC();
        threadContexts.push_back(tc);
    }


    /*if (params.checker) {
        fatal("The CClass model doesn't support checking (yet)\n");
    }*/

    pipeline = new cclass::Pipeline(*this, params);
    //activityRecorder = pipeline->getActivityRecorder();
    fetchEventWrapper = NULL;
}

CClassCPU::~CClassCPU()
{
    //delete pipeline;

    if (fetchEventWrapper != NULL)
        delete fetchEventWrapper;

    for (ThreadID thread_id = 0; thread_id < threads.size(); thread_id++) {
        delete threads[thread_id];
    }
}

void
CClassCPU::init()
{
    BaseCPU::init();

    if (!params().switched_out && system->getMemoryMode() != enums::timing) {
        fatal("The CClass CPU requires the memory system to be in "
            "'timing' mode.\n");
    }
}

/** Stats interface from SimObject (by way of BaseCPU) */

void
CClassCPU::regStats()
{
    BaseCPU::regStats();
    pipeline->regStats();

}

void
CClassCPU::serializeThread(CheckpointOut &cp, ThreadID thread_id) const
{
    threads[thread_id]->serialize(cp);
}

void
CClassCPU::unserializeThread(CheckpointIn &cp, ThreadID thread_id)
{
    threads[thread_id]->unserialize(cp);
}

void
CClassCPU::serialize(CheckpointOut &cp) const
{
    pipeline->serialize(cp);
    BaseCPU::serialize(cp);
}

void
CClassCPU::unserialize(CheckpointIn &cp)
{
    pipeline->unserialize(cp);
    BaseCPU::unserialize(cp);
}

void
CClassCPU::wakeup(ThreadID tid)
{
    //DPRINTF(Drain, "[tid:%d] CClassCPU wakeup\n", tid);
    assert(tid < numThreads);

    if (threads[tid]->status() == ThreadContext::Suspended) {
        threads[tid]->activate();
    }
}

void
CClassCPU::startup()
{
    DPRINTF(CClassCPU, "CClassCPU startup\n");

    BaseCPU::startup();
    //for now only single thread 
   //for (ThreadID tid = 0; tid < numThreads; tid++)
    pipeline->wakeupFetch(0);
    
}

/*
DrainState
CClassCPU::drain()
{
    // Deschedule any power gating event (if any)
    deschedulePowerGatingEvent();

    if (switchedOut()) {
        DPRINTF(Drain, "CClass CPU switched out, draining not needed.\n");
        return DrainState::Drained;
    }

    DPRINTF(Drain, "CClassCPU drain\n"); */

    /* Need to suspend all threads and wait for Execute to idle.
     * Tell Fetch1 not to fetch */
    /*
    if (pipeline->drain()) {
        DPRINTF(Drain, "CClassCPU drained\n");
        return DrainState::Drained;
    } else {
        DPRINTF(Drain, "CClassCPU not finished draining\n");
        return DrainState::Draining;
    }
}*/

/*
void
CClassCPU::signalDrainDone()
{
    DPRINTF(Drain, "CClassCPU drain done\n");
    Drainable::signalDrainDone();
}
*/
/*
void
CClassCPU::drainResume()
{
    /* When taking over from another cpu make sure lastStopped
     * is reset since it might have not been defined previously
     * and might lead to a stats corruption */
  /*  pipeline->resetLastStopped();

    if (switchedOut()) {
        DPRINTF(Drain, "drainResume while switched out.  Ignoring\n");
        return;
    }

    DPRINTF(Drain, "CClassCPU drainResume\n");

    if (!system->isTimingMode()) {
        fatal("The CClass CPU requires the memory system to be in "
            "'timing' mode.\n");
    }

    for (ThreadID tid = 0; tid < numThreads; tid++){
        wakeup(tid);
    }

    pipeline->drainResume();

    // Reschedule any power gating event (if any)
    schedulePowerGatingEvent();
}

void
CClassCPU::memWriteback()
{
    DPRINTF(Drain, "CClassCPU memWriteback\n");
}

void
CClassCPU::switchOut()
{
    DPRINTF(CClassCPU, "CClassCPU switchOut\n");

    assert(!switchedOut());
    BaseCPU::switchOut();

    /* Check that the CPU is drained? */
    /*
    activityRecorder->reset();
}

void
CClassCPU::takeOverFrom(BaseCPU *old_cpu)
{
    DPRINTF(CClassCPU, "CClassCPU takeOverFrom\n");

    BaseCPU::takeOverFrom(old_cpu);
}
*/
void
CClassCPU::activateContext(ThreadID thread_id)
{
    DPRINTF(CClassCPU, "ActivateContext thread: %d\n", thread_id);

    /* Do some cycle accounting.  lastStopped is reset to stop the
     *  wakeup call on the pipeline from adding the quiesce period
     *  to BaseCPU::numCycles */
    
    //stats.quiesceCycles += pipeline->cyclesSinceLastStopped();
    pipeline->resetLastStopped();

    /* Wake up the thread, wakeup the pipeline tick */
    
    threads[thread_id]->activate();
    wakeupOnEvent(cclass::Pipeline::CPUStageId);
    if (!threads[thread_id]->getUseForClone())//the thread is not cloned
    {
        pipeline->wakeupFetch(thread_id);
    } else { //the thread from clone
        if (fetchEventWrapper != NULL)
            delete fetchEventWrapper;
        fetchEventWrapper = new EventFunctionWrapper([this, thread_id]
                  { pipeline->wakeupFetch(thread_id); }, "wakeupFetch");
        schedule(*fetchEventWrapper, clockEdge(Cycles(0)));
    }

    BaseCPU::activateContext(thread_id);
    //std::cout << "This worksss" << std::endl;

}

void
CClassCPU::suspendContext(ThreadID thread_id)
{
    DPRINTF(CClassCPU, "SuspendContext %d\n", thread_id);

    threads[thread_id]->suspend();

    BaseCPU::suspendContext(thread_id);
}

void
CClassCPU::wakeupOnEvent(unsigned int stage_id)
{
    //DPRINTF(Quiesce, "Event wakeup from stage %d\n", stage_id);

    /* Mark that some activity has taken place and start the pipeline */
    //activityRecorder->activateStage(stage_id);
    pipeline->start();
}

Port &
CClassCPU::getInstPort()
{
    return pipeline->getInstPort();

}

Port &
CClassCPU::getDataPort()
{
    return pipeline->getDataPort();
}

Counter
CClassCPU::totalInsts() const
{
    Counter ret = 0;

    //for (auto i = threads.begin(); i != threads.end(); i ++)
        //ret += (*i)->numInst;

    return ret;
}

Counter
CClassCPU::totalOps() const
{
    Counter ret = 0;

    //for (auto i = threads.begin(); i != threads.end(); i ++)
        //ret += (*i)->numOp;

    return ret;
}


} // namespace gem5
