# -*- mode:python -*-


Import('*')

if env['CONF']['BUILD_ISA']:
    SimObject('BaseCClassCPU.py', sim_objects=['CClassOpClass', 'CClassOpClassSet', 'CClassFUTiming', 'CClassFU','CClassFUPool', 'BaseCClassCPU'],enums=['CClassThreadPolicy'])

#    Source('activity.cc')
    Source('cpu.cc')
    Source('decode.cc')
    Source('dyn_inst.cc')
    Source('exec_context.cc')
    Source('execute.cc')
    Source('fetch1.cc')
    Source('fetch2.cc')
    Source('func_unit.cc')
    Source('memory.cc')
#    Source('lsq.cc')
    Source('pipe_data.cc')
    Source('pipeline.cc')
    Source('scoreboard.cc')
    Source('writeback.cc')
#    Source('stats.cc')

    DebugFlag('CClassCPU', 'CClass CPU-level events')
    DebugFlag('CClassFetch1', 'CClass fetch1 stage')
    DebugFlag('CClassFetch2', 'CClass fetch2 stage')
    DebugFlag('CClassDecode', 'CClass decode stage')


    DebugFlag('CClassExecute', 'CClass execute stage')
    DebugFlag('CClassMemory', 'CClass memory accesses')
    DebugFlag('CClassWriteBack','CClass write back stage')
    DebugFlag('CClassScoreboard', 'CClass Execute register scoreboard')
    DebugFlag('CClassTrace', 'CClassTrace cycle-by-cycle state trace')
    DebugFlag('CClassTiming', 'Extra timing for instructions')
#    DebugFlag('CClassInterrupt', 'CClass interrupt handling')

    # For backwards compatibility
    SimObject('CClassCPU.py', sim_objects=[], tags=['isa'])
